---
extends: default
rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 150
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    indent-sequences: consistent
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
