apiVersion: v1
kind: Pod
metadata:
  name: logd-manager
  labels:
    env: test
spec:
  containers:
  - name: logd-manager
    image: snapple49/logd-manager:pctl-1.7.10
    imagePullPolicy: IfNotPresent
    command: ["/usr/bin/tail"]
    args: ["-f", "/dev/null"]
    resources:
      limits:
        cpu: "1"
        memory: "1000Mi"
      requests:
        cpu: "250m"
        memory: "500Mi"
    volumeMounts:
    - name: creds
      mountPath: "/etc/creds"
      readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: logd-chembl-mysql
      items:
      - key: mysql-root-password
        path: rootpw
  nodeSelector:
    acceleration: none