---
apiVersion: v1
kind: Pod
metadata:
  name: manager-pod
  labels:
    env: test
spec:
  containers:
  - name: manager-pod
    image: pharmbio/manager-pod:pctl-1.7.10
    imagePullPolicy: IfNotPresent
    command: ["/usr/bin/tail"]
    args: ["-f", "/dev/null"]
    resources:
      limits:
        cpu: "4"
        memory: "4G"
      requests:
        cpu: "1000m"
        memory: "2G"
    volumeMounts:
    - name: creds
      mountPath: "/etc/creds"
      readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: chembl-mysql
      items:
      - key: mysql-root-password
        path: rootpw
  nodeSelector:
    acceleration: none
